-- =========================================================
-- EXTENSIONS
-- =========================================================
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;

-- =========================================================
-- 1. USERS & AUTHORIZATION
-- =========================================================

CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER', 'MERCHANT', 'SHIPPER')),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    avatar_url TEXT,
    is_verified BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE user_addresses (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    address_name VARCHAR(50), 
    full_address TEXT NOT null,
    location GEOGRAPHY(Point, 4326) NOT NULL, -- Point(Kinh độ, Vĩ độ), 4326 là mã chuẩn của hệ tọa độ toàn cầu (WGS84)
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index không gian để query địa chỉ nhanh hơn
CREATE INDEX idx_user_addresses_location ON user_addresses USING GIST (location);

-- Ràng buộc 1 địa chỉ mặc định
CREATE UNIQUE INDEX idx_only_one_default_address 
ON user_addresses (user_id) 
WHERE (is_default IS TRUE);

-- Bảng Token
CREATE TABLE user_tokens (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    type VARCHAR(20) NOT NULL, 
    expires_at TIMESTAMPTZ NOT NULL,
    is_revoked BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- 2. RESTAURANTS & PRODUCTS
-- =========================================================

CREATE TABLE restaurants (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    location GEOGRAPHY(Point, 4326) NOT NULL,
    description TEXT,
    logo_url TEXT,
    approval_status VARCHAR(20) DEFAULT 'PENDING',
    rating_avg NUMERIC(2,1) DEFAULT 0 CHECK (rating_avg BETWEEN 0 AND 5),
    review_count INT DEFAULT 0 CHECK (review_count >= 0),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index không gian cho nhà hàng
CREATE INDEX idx_restaurants_location_gist ON restaurants USING GIST (location);

-- Bảng giờ hoạt động (Giữ nguyên - Rất tốt cho logic kiểm tra quán đóng/mở)
CREATE TABLE restaurant_operating_hours (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID REFERENCES restaurants(id) ON DELETE CASCADE,
    day_of_week VARCHAR(10),
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    is_closed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Danh mục: Phân nhóm menu (Ví dụ: "Món khai vị", "Đồ uống")
CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_restaurant_category_name UNIQUE (restaurant_id, name)
);


-- Bảng Sản phẩm: Hỗ trợ CRUD và trạng thái kinh doanh
CREATE TABLE products (
    id UUID PRIMARY KEY,
    restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    category_id INT REFERENCES categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    description TEXT,
    image_url TEXT,
    rating_avg NUMERIC(2,1) DEFAULT 0 CHECK (rating_avg BETWEEN 0 AND 5),
    review_count INT DEFAULT 0 CHECK (review_count >= 0),
    is_available BOOLEAN DEFAULT true, 
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_products_restaurant_category 
ON products (restaurant_id, category_id);

-- =========================================================
-- 3. SHIPPING (SHIPPER & CONFIG)
-- =========================================================
CREATE TABLE shippers (
    id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    vehicle_info VARCHAR(100),
    license_plate VARCHAR(20) UNIQUE,
    is_online BOOLEAN DEFAULT false,
    is_busy BOOLEAN DEFAULT false,
    approval_status VARCHAR(20) DEFAULT 'PENDING',
    location GEOGRAPHY(Point, 4326), -- Vị trí dưới dạng Point (Kinh độ, Vĩ độ)
    rating_avg NUMERIC(2,1) DEFAULT 0 CHECK (rating_avg BETWEEN 0 AND 5),
    review_count INT DEFAULT 0 CHECK (review_count >= 0),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tạo Index không gian để tìm shipper cực nhanh
CREATE INDEX idx_shippers_location ON shippers USING GIST (location);

CREATE TABLE shipping_configs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100),           -- Ví dụ: "Giá ngày thường", "Giá Tết Nguyên Đán"
    base_fee NUMERIC(12,2) NOT NULL,
    base_distance_km NUMERIC(5,2) NOT NULL,
    fee_per_km NUMERIC(12,2) NOT NULL,
    is_active BOOLEAN DEFAULT true,
    active_from TIMESTAMPTZ DEFAULT NOW(),
    active_to TIMESTAMPTZ,               -- Có thể để trống nếu là giá vĩnh viễn
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- 4. PROMOTION
-- =========================================================

CREATE TABLE vouchers (
    id UUID PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    discount_type VARCHAR(20) NOT NULL, -- 'FIXED', 'PERCENTAGE'
    discount_value NUMERIC(12,2) NOT NULL,
    target_type VARCHAR(20) DEFAULT 'ORDER', -- 'ORDER', 'SHIPPING'
    min_order_value NUMERIC(12,2) DEFAULT 0,
    max_discount_amount NUMERIC(12,2),
    usage_limit INT DEFAULT 1,
    used_count INT DEFAULT 0,
    expiry_date TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- 5. ORDERS
-- =========================================================
CREATE TABLE orders (
    id UUID PRIMARY KEY,
    order_code VARCHAR(20) UNIQUE NOT NULL,
    customer_id UUID REFERENCES users(id),
    restaurant_id UUID REFERENCES restaurants(id),
    shipper_id UUID REFERENCES shippers(id),
    voucher_id UUID REFERENCES vouchers(id),
    notes TEXT, -- Ghi chú chung cho đơn hàng (VD: "Giao hàng cẩn thận", "Khách muốn gọi điện trước khi giao")

    -- Financial Snapshot (Lưu giá tại thời điểm đặt)
    subtotal NUMERIC(12,2) NOT NULL,       -- Tổng tiền món ăn
    shipping_fee NUMERIC(12,2) NOT NULL,    -- Phí ship tại thời điểm đó
    discount_amount NUMERIC(12,2) DEFAULT 0, -- Số tiền được giảm
    total_amount NUMERIC(12,2) NOT NULL,    -- Số tiền khách phải trả (Final)

    -- Status Snapshot
    order_status VARCHAR(30) NOT NULL,     -- PENDING, CONFIRMED, SHIPPING, COMPLETED, CANCELLED
    payment_status VARCHAR(30) NOT NULL,   -- UNPAID, PAID, REFUNDED

    -- GPS Snapshot & PostGIS (Lưu địa điểm giao hàng)
    delivery_address TEXT NOT NULL,
    delivery_location GEOGRAPHY(Point, 4326) NOT NULL,

    -- Audit Timestamps
    placed_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_orders_delivery_loc ON orders USING GIST (delivery_location);

CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id),
    quantity INT NOT NULL CHECK (quantity > 0),
    price_at_purchase NUMERIC(12,2) NOT NULL, -- Lưu giá món ăn tại thời điểm đặt đơn (Tránh việc quán đổi giá sau này)
    notes TEXT -- Ví dụ: "Không hành", "Nhiều cay"
);

CREATE TABLE order_status_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL, -- Trạng thái mới
    changed_by UUID REFERENCES users(id), -- Xác định người thực hiện hành động (Admin, Merchant, Shipper, Customer)
    reason TEXT, -- Lý do (Đặc biệt quan trọng khi status = 'CANCELLED')
    changed_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- 6. PAYMENTS & WALLET
-- =========================================================
-- Lưu thông tin thanh toán từ cổng thanh toán (VNPay, Momo...)
CREATE TABLE payments (
    id UUID PRIMARY KEY,
    order_id UUID UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    vnp_txn_ref VARCHAR(100) UNIQUE, -- Mã giao dịch của phía bạn gửi đi
    vnp_transaction_no VARCHAR(100), -- Mã giao dịch trả về từ VNPay
    amount NUMERIC(12,2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL, -- PENDING, SUCCESS, FAILED
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ví tiền: Lưu số dư hiện tại và thông tin rút tiền duy nhất
CREATE TABLE wallets (
    id UUID PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    balance NUMERIC(14,2) DEFAULT 0 CHECK (balance >= 0), -- Thông tin ngân hàng mặc định để rút tiền
    bank_name VARCHAR(100),
    bank_account_number VARCHAR(50),
    bank_account_holder VARCHAR(100),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    version BIGINT DEFAULT 0
);

-- Sổ cái: Lưu MỌI biến động tiền bạc (Cộng tiền đơn hàng, Trừ tiền rút...)
CREATE TABLE wallet_transactions (
    id UUID PRIMARY KEY,
    wallet_id UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    order_id UUID REFERENCES orders(id) ON DELETE SET NULL, -- Có thể NULL nếu là giao dịch rút tiền
    transaction_code VARCHAR(50) UNIQUE NOT NULL, -- Mã tham chiếu nội bộ
    type VARCHAR(20) NOT NULL, -- 'ORDER_REVENUE', 'WITHDRAWAL', 'REFUND'
    amount NUMERIC(14,2) NOT NULL, -- Số tiền biến động (VD: +50000 hoặc -50000)
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Quản lý yêu cầu rút tiền của Merchant/Shipper
CREATE TABLE payout_requests (
    id UUID PRIMARY KEY,
    wallet_id UUID NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    note TEXT, -- Ghi chú (VD: Mã giao dịch ngân hàng hoặc lý do từ chối)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    transaction_id UUID REFERENCES wallet_transactions(id) -- Lưu vết transaction nào đã thực hiện việc trừ tiền này
);

-- =========================================================
-- 7. REVIEWS
-- =========================================================
-- Đánh giá tổng quan đơn hàng & nhà hàng
CREATE TABLE order_reviews (
    id UUID PRIMARY KEY,
    order_id UUID UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
    restaurant_id UUID REFERENCES restaurants(id),
    restaurant_rating INT CHECK (restaurant_rating BETWEEN 1 AND 5), -- Sao cho nhà hàng (để tính rating_avg cho nhà hàng)
    comment TEXT, -- Nội dung đánh giá chung
    shipper_id UUID REFERENCES shippers(id),
    shipper_rating INT CHECK (shipper_rating BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_visible BOOLEAN DEFAULT true,
    restaurant_reply TEXT,
    replied_at TIMESTAMPTZ
);

-- Đánh giá chi tiết từng món (Chỉ hiện khi khách muốn đánh giá sâu)
CREATE TABLE order_item_reviews (
    id UUID PRIMARY KEY,
    order_review_id UUID REFERENCES order_reviews(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    rating INT CHECK (rating BETWEEN 1 AND 5), -- Sao cho món ăn (để tính rating cho món ăn đó)
    comment TEXT,
    image_url TEXT, -- Khách thường chụp ảnh món ăn cụ thể
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_visible BOOLEAN DEFAULT true
);

-- =========================================================
-- 8. AI EMBEDDINGS (pgvector)
-- =========================================================
CREATE TABLE restaurant_embeddings (
    restaurant_id UUID PRIMARY KEY REFERENCES restaurants(id) ON DELETE CASCADE,
    embedding vector(768)
);

CREATE TABLE product_embeddings (
    product_id UUID PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
    embedding vector(768)
);

CREATE INDEX idx_product_embedding 
ON product_embeddings 
USING hnsw (embedding vector_cosine_ops);

CREATE INDEX idx_restaurant_embedding 
ON restaurant_embeddings 
USING hnsw (embedding vector_cosine_ops);

CREATE TABLE system_configs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(50) UNIQUE NOT NULL,
    value TEXT NOT NULL, 
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
